### PR TITLE
Switch to Maven

### PR DESCRIPTION
**Pull request by ctrueden**
As discussed in #9.

* Move source files to standard location in src/main/java
* Move resources to standard location in src/main/resources
* Remove Ant build system
* Remove Eclipse files (use File > Import > Existing Maven Project)

A Maven-based build system has many advantages, including:

* Enables project development from many IDEs, not just Eclipse.
* Enables building from the command line.
* Simplifies execution of any future continuous integration tests.
* Standard project structure is quicker for new devs to understand.
* Structured metadata in pom.xml describes project details.

### CODE REVIEW

**Comment by ctrueden** [comment]
One question: in the [`<developers>` section](https://github.com/deepimagej/deepimagej-plugin/pull/14/commits/eb9c0f947f9f52eb2376cfdcc806b3665d0649cb#diff-600376dffeb79835ede4a0b285078036R31-R102) I was not sure of the information in some cases. I listed the developers from the DeepImageJ preprint on bioaRxiv, in same order. But I do not know the GitHub ID of Laurène Donati. What should we put for that? I also did not know what [roles](https://imagej.net/Team) each person wants to declare.

**Comment by ctrueden** [comment]
@esgomezm @carlosuc3m @arrmunoz dasv74 What do you think? If you let me know the correct developers info, I will finalize this PR.

**Comment by esgomezm** [comment]
Could you please leave only Carlos, Daniel, Arrate and me? Unless it has a significant impact, I'd leave the roles as they are right now. I can also update it after the PR is accepted.

**Comment by ctrueden** [comment]
@esgomezm wrote:
> Could you please leave only Carlos, Daniel, Arrate and me?

Done.

> Unless it has a significant impact, I'd leave the roles as they are right now.

It's just about communicating expectations to your users. For example, all four of you are listed as `lead` implies you all share in decisions about the strategic directions of the project. So the main impact will be social within the community.

I think this branch is ready to go now.

**Comment by carlosuc3m** [comment]
Thanks a lot for your effort @ctrueden . We will keep you updated

**Pull request merged**
